---
- hosts: awsTest

  vars_files:
  - vars.yml

  # pre_tasks:
  #   - name: Update apt cache if needed
  #     apt: update_cache=yes cache_valid_time=3600
  #     become: yes

  handlers:
    - name: restart solr
      service: name=solr state=restarted
      become: yes

  tasks:
    - name: Install java 8
      apt: name=openjdk-8-jdk state=present
      become: yes

    - name: Download Solr
      get_url:
        url: "https://archive.apache.org/dist/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz"
        dest: "~/solr-{{ solr_version }}.tgz"
        checksum: "{{ solr_checksum }}"

    - name: Unzip solr
      unarchive: 
        src: "~/solr-{{ solr_version }}.tgz"
        dest: "~"
        copy: no
        creates: "~/solr-{{ solr_version }}/README.txt"

    - name: Run solr in cloud mode
      shell: "./solr -c"
      args:
        chdir: "~/solr-{{ solr_version }}/bin"
      register: foo

    - name: Set environment variables
      lineinfile: 
        dest: /etc/environment
        line: "{{ item }}"
        create: yes
      with_items:
        - export SOLR_HOME="/home/ubuntu/solr-7.4.0/server/solr"
      become: yes

    - name: Checkout montebello from codecommit
      git:
        repo: "ssh://git-codecommit.ap-southeast-2.amazonaws.com/v1/repos/montebello"
        dest: "~/pipeline"
        version: "MBL-29"
        accept_hostkey: yes

    - name: Install python3 package
      pip:
        name:
          - pysolr
          - lxml
        executable: pip3
      become: yes

    - name: Configurate solr
      shell: "./conf.sh"
      args:
        chdir: "~/pipeline/scripts/dev"
      register: config_result

    - name: Configurate solr
      shell: "yes | ./index.sh"
      args:
        chdir: "~/pipeline/scripts/dev"
      register: index_result
      
  ## run conf.sh index.sh

## running solr as service
    # - name: Run Solr installation script.
    #   shell: >
    #     sudo
    #     ~/solr-{{ solr_version }}/bin/install_solr_service.sh
    #     ~/solr-{{ solr_version }}.tgz
    #     -i /usr/bin
    #     -d /var/solr
    #     -u solr
    #     -s solr
    #     -p 8983
        
    # - name: Ensure solr is started and enabled on boot.
    #   service: name=solr state=started enabled=yes
 